using System.ComponentModel.DataAnnotations;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcCrudDB.Context
{
    public class tbl_studentBase1
    {
        [Required(ErrorMessage = "Required")]
        public string Description { get; set; }
        [Required(ErrorMessage = "Required")]

        [EmailAddress]   /*EmailAddress is controlled, Emai is avlid or not*/
        public string Email { get; set; }
        [Required(ErrorMessage = "Required")]
        public string Fname { get; set; }
        public int ID { get; set; }
        [Required(ErrorMessage = "Required")]

        [MinLength(11, ErrorMessage = "Mobile Number should not be 11 digit")]
        public string Mobile { get; set; }
        [Required(ErrorMessage = "Required")]
        public string Name { get; set; }
    }
}